### ISSUE TITLE
How can I get the file"tricon"?

### ISSUE THREAD

**Issue by vikyou** [wooner49/TriCL#1]
<img width="495" alt="1694421560528" src="https://github.com/wooner49/TriCL/assets/44255757/a2380e27-18dd-4ce4-b22e-40187a12e861">

**Comment by wooner49** [comment]
That is a typo (tricon -> TriCL). 
I will reflect this in the code. Thank you for letting me know.

**Comment by vikyou** [comment]
You're welcome! Thanks for the work!
